spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  application:
    name: twocats-admin
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  devtools:
    restart:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 9000

app:
  home-info:
    title: 首页
    href: /admin/welcome
  logo-info:
    title: 两只猫管理后台
    image: /images/logo.png
    href: /admin/index
debug: false
